apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: diyar-ns
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxUnavailable: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - image: quay.io/kordboydm/ie_frontend:new
          imagePullPolicy: Always
          name: frontend
          ports:
            - containerPort: 3000
          resources:
            limits:
              memory: "333Mi"
              cpu: "333m"
            requests:
              memory: "333Mi"
              cpu: "333m"
